name: Build and Release
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
  workflow_dispatch:
jobs:
  build:
    name: Build and Deploy to GitHub Releases
    runs-on: windows-latest
    steps:
      - name: Build and Deploy
        uses: distance-modding/action.buildanddeploy@v1.0.1